[package]
version = "0.0.1"
name = "bongbong"
edition = "2024"

[[bin]]
path = "./src/balls.rs"
name = "balls"

[[bin]]
path = "./src/main.rs"
name = "bongbong"


[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
sola-raylib = {
  version = "6.2.0" 
  # features = ["serde"] 
}
