version = 1

[cells."34,14"]
kind = "wall"
material = "wood"

[cells."23,8"]
kind = "wall"
material = "wood"

[cells."24,4"]
kind = "wall"
material = "wood"

[cells."30,8"]
kind = "pickup"
pickup = "ammo"

[cells."33,5"]
kind = "wall"
material = "brick"

[cells."16,4"]
kind = "wall"
material = "wood"

[cells."34,15"]
kind = "wall"
material = "wood"

[cells."5,1"]
kind = "wall"
material = "brick"

[cells."20,9"]
kind = "road"

[cells."18,5"]
kind = "wall"
material = "wood"

[cells."7,14"]
kind = "wall"
material = "glass"

[cells."8,11"]
kind = "wall"
material = "glass"

[cells."20,10"]
kind = "road"

[cells."10,9"]
kind = "wall"
material = "wood"

[cells."34,10"]
kind = "wall"
material = "wood"

[cells."8,5"]
kind = "wall"
material = "brick"

[cells."7,11"]
kind = "wall"
material = "glass"

[cells."23,4"]
kind = "wall"
material = "wood"

[cells."19,13"]
kind = "wall"
material = "wood"

[cells."23,11"]
kind = "wall"
material = "wood"

[cells."5,5"]
kind = "wall"
material = "brick"

[cells."9,4"]
kind = "wall"
material = "brick"

[cells."34,8"]
kind = "wall"
material = "wood"

[cells."24,3"]
kind = "wall"
material = "wood"

[cells."6,17"]
kind = "wall"
material = "brick"

[cells."34,5"]
kind = "wall"
material = "brick"

[cells."13,13"]
kind = "wall"
material = "wood"

[cells."4,9"]
kind = "wall"
material = "iron"

[cells."31,16"]
kind = "wall"
material = "iron"

[cells."13,10"]
kind = "wall"
material = "wood"

[cells."4,1"]
kind = "wall"
material = "glass"

[cells."7,4"]
kind = "wall"
material = "brick"

[cells."6,3"]
kind = "pickup"
pickup = "ammo"

[cells."1,5"]
kind = "wall"
material = "brick"

[cells."22,4"]
kind = "wall"
material = "wood"

[cells."35,18"]
kind = "wall"
material = "wood"

[cells."33,16"]
kind = "wall"
material = "wood"

[cells."25,18"]
kind = "wall"
material = "glass"

[cells."29,18"]
kind = "wall"
material = "wood"

[cells."11,17"]
kind = "wall"
material = "iron"

[cells."23,7"]
kind = "wall"
material = "brick"

[cells."29,4"]
kind = "wall"
material = "glass"

[cells."24,13"]
kind = "wall"
material = "brick"

[cells."11,5"]
kind = "wall"
material = "glass"

[cells."9,12"]
kind = "wall"
material = "glass"

[cells."9,5"]
kind = "wall"
material = "brick"

[cells."8,14"]
kind = "wall"
material = "glass"

[cells."8,4"]
kind = "pickup"
pickup = "ammo"

[cells."12,2"]
kind = "wall"
material = "brick"

[cells."9,14"]
kind = "wall"
material = "glass"

[cells."4,10"]
kind = "wall"
material = "iron"

[cells."6,13"]
kind = "wall"
material = "glass"

[cells."3,5"]
kind = "wall"
material = "glass"

[cells."13,11"]
kind = "wall"
material = "wood"

[cells."36,20"]
kind = "wall"
material = "wood"

[cells."13,12"]
kind = "wall"
material = "wood"

[cells."31,18"]
kind = "wall"
material = "wood"

[cells."10,5"]
kind = "wall"
material = "glass"

[cells."17,4"]
kind = "wall"
material = "wood"

[cells."24,10"]
kind = "wall"
material = "brick"

[cells."8,3"]
kind = "pickup"
pickup = "ammo"

[cells."21,5"]
kind = "wall"
material = "wood"

[cells."28,18"]
kind = "wall"
material = "wood"

[cells."15,3"]
kind = "wall"
material = "wood"

[cells."18,4"]
kind = "wall"
material = "wood"

[cells."12,3"]
kind = "wall"
material = "brick"

[cells."15,4"]
kind = "wall"
material = "wood"

[cells."6,18"]
kind = "wall"
material = "brick"

[cells."5,4"]
kind = "wall"
material = "brick"

[cells."24,7"]
kind = "wall"
material = "brick"

[cells."23,3"]
kind = "wall"
material = "wood"

[cells."9,11"]
kind = "wall"
material = "glass"

[cells."34,6"]
kind = "wall"
material = "wood"

[cells."23,12"]
kind = "wall"
material = "wood"

[cells."3,20"]
kind = "pickup"
pickup = "ammo"

[cells."6,9"]
kind = "wall"
material = "wood"

[cells."20,13"]
kind = "wall"
material = "wood"

[cells."12,17"]
kind = "wall"
material = "iron"

[cells."14,4"]
kind = "wall"
material = "wood"

[cells."13,9"]
kind = "wall"
material = "wood"

[cells."30,15"]
kind = "wall"
material = "iron"

[cells."18,10"]
kind = "wall"
material = "wood"

[cells."6,16"]
kind = "wall"
material = "brick"

[cells."13,14"]
kind = "wall"
material = "wood"

[cells."9,9"]
kind = "wall"
material = "wood"

[cells."6,14"]
kind = "wall"
material = "glass"

[cells."38,22"]
kind = "wall"
material = "iron"

[cells."33,18"]
kind = "wall"
material = "wood"

[cells."1,2"]
kind = "wall"
material = "brick"

[cells."7,3"]
kind = "wall"
material = "brick"

[cells."28,4"]
kind = "wall"
material = "glass"

[cells."4,5"]
kind = "wall"
material = "glass"

[cells."13,7"]
kind = "pickup"
pickup = "health"

[cells."31,15"]
kind = "wall"
material = "iron"

[cells."18,9"]
kind = "wall"
material = "wood"

[cells."17,3"]
kind = "wall"
material = "wood"

[cells."7,9"]
kind = "wall"
material = "wood"

[cells."7,1"]
kind = "wall"
material = "brick"

[cells."10,17"]
kind = "wall"
material = "iron"

[cells."8,1"]
kind = "wall"
material = "brick"

[cells."8,12"]
kind = "frog"

[cells."9,13"]
kind = "wall"
material = "glass"

[cells."30,16"]
kind = "wall"
material = "iron"

[cells."23,13"]
kind = "wall"
material = "wood"

[cells."24,12"]
kind = "wall"
material = "brick"

[cells."32,16"]
kind = "wall"
material = "wood"

[cells."25,4"]
kind = "wall"
material = "wood"

[cells."6,12"]
kind = "wall"
material = "glass"

[cells."26,18"]
kind = "wall"
material = "glass"

[cells."2,1"]
kind = "wall"
material = "brick"

[cells."23,10"]
kind = "wall"
material = "wood"

[cells."22,13"]
kind = "wall"
material = "wood"

[cells."3,1"]
kind = "wall"
material = "brick"

[cells."7,5"]
kind = "wall"
material = "brick"

[cells."36,18"]
kind = "wall"
material = "wood"

[cells."24,9"]
kind = "wall"
material = "brick"

[cells."21,4"]
kind = "wall"
material = "wood"

[cells."34,13"]
kind = "wall"
material = "wood"

[cells."39,21"]
kind = "wall"
material = "iron"

[cells."23,9"]
kind = "wall"
material = "wood"

[cells."10,1"]
kind = "wall"
material = "brick"

[cells."6,11"]
kind = "wall"
material = "glass"

[cells."30,18"]
kind = "wall"
material = "wood"

[cells."2,5"]
kind = "wall"
material = "brick"

[cells."12,5"]
kind = "wall"
material = "glass"

[cells."6,5"]
kind = "wall"
material = "brick"

[cells."40,21"]
kind = "wall"
material = "iron"

[cells."25,5"]
kind = "wall"
material = "wood"

[cells."34,9"]
kind = "wall"
material = "wood"

[cells."18,13"]
kind = "wall"
material = "wood"

[cells."40,22"]
kind = "wall"
material = "iron"

[cells."34,11"]
kind = "wall"
material = "wood"

[cells."34,18"]
kind = "wall"
material = "wood"

[cells."6,1"]
kind = "wall"
material = "brick"

[cells."21,13"]
kind = "wall"
material = "wood"

[cells."24,11"]
kind = "wall"
material = "brick"

[cells."16,3"]
kind = "wall"
material = "wood"

[cells."12,4"]
kind = "wall"
material = "brick"

[cells."36,21"]
kind = "wall"
material = "wood"

[cells."24,8"]
kind = "wall"
material = "brick"

[cells."1,4"]
kind = "wall"
material = "brick"

[cells."8,9"]
kind = "wall"
material = "wood"

[cells."24,18"]
kind = "wall"
material = "glass"

[cells."14,5"]
kind = "wall"
material = "wood"

[cells."1,3"]
kind = "wall"
material = "brick"

[cells."11,1"]
kind = "wall"
material = "brick"

[cells."39,22"]
kind = "wall"
material = "iron"

[cells."34,16"]
kind = "wall"
material = "wood"

[cells."6,4"]
kind = "pickup"
pickup = "ammo"

[cells."9,1"]
kind = "wall"
material = "brick"

[cells."6,19"]
kind = "wall"
material = "brick"

[cells."12,1"]
kind = "wall"
material = "brick"

[cells."22,3"]
kind = "wall"
material = "wood"

[cells."18,8"]
kind = "wall"
material = "wood"

[cells."34,7"]
kind = "wall"
material = "wood"

[cells."27,14"]
kind = "pickup"
pickup = "health"

[cells."32,18"]
kind = "wall"
material = "wood"

[cells."34,12"]
kind = "wall"
material = "wood"

[cells."36,19"]
kind = "wall"
material = "wood"
