//! The anchors of the tank art, generated by `tools/spritegen/tankdesign/export.py`
//! from the `vanguard` design line (`lines/vanguard.py`) - regenerate, never edit by hand.
//! Every point is in design pixels from the pivot: x to the right, y toward
//! the tail (the gun points to -y), in the hull's frame (lamps) or the
//! turret's (muzzles, spotlights, modules). One design pixel is `Tank::scale`
//! world pixels. Indexed by chassis row (`TankKind::row`).

/// Each chassis's design name, for the dev tools.
pub const CODENAMES: [&str; 12] = ["Lynx", "Bulwark", "Maul", "Yew", "Hornet", "Shade", "Aegis", "Warhog", "Floe", "Trebuchet", "Colossus", "Behemoth"];

/// The headlamps a night throws its cones from (hull frame).
pub const HEADLIGHTS: [&[(f32, f32)]; 12] = [
    &[(-4.5, -4.5), (4.5, -4.5)], // scout
    &[(-5.5, -9.5), (5.5, -9.5)], // assault
    &[(-6.5, -10.5), (6.5, -10.5)], // breaker
    &[(-5.5, -9.5), (5.5, -9.5)], // longbow
    &[(-4.5, -7.5), (4.5, -7.5)], // flak
    &[(-2.5, -7.5), (2.5, -7.5)], // wraith
    &[(-3.5, -9.5), (3.5, -9.5)], // warden
    &[(-6.5, -8.5), (6.5, -8.5)], // ravager
    &[(-4.5, -6.5), (4.5, -6.5)], // glacier
    &[(-4.5, -9.5), (4.5, -9.5)], // obelisk
    &[(-9.5, -11.5), (-6.5, -11.5), (6.5, -11.5), (9.5, -11.5)], // titan
    &[(-7.5, -12.5), (-5.5, -12.5), (5.5, -12.5), (7.5, -12.5)], // leviathan
];

/// Turret searchlights: (x, y, degrees off the gun line) - the cone
/// follows the aim (turret frame).
pub const SPOTLIGHTS: [&[(f32, f32, f32)]; 12] = [
    &[], // scout
    &[], // assault
    &[], // breaker
    &[], // longbow
    &[], // flak
    &[], // wraith
    &[], // warden
    &[], // ravager
    &[], // glacier
    &[], // obelisk
    &[(-6.5, -3.5, 0.0)], // titan
    &[], // leviathan
];

/// The main gun's muzzles at rest, one per barrel (turret frame).
pub const GUN_MUZZLES: [&[(f32, f32)]; 12] = [
    &[(0.0, -15.0)], // scout
    &[(-3.0, -13.0), (3.0, -13.0)], // assault
    &[(0.0, -12.0)], // breaker
    &[(0.0, -17.0)], // longbow
    &[(-3.0, -11.0), (3.0, -11.0)], // flak
    &[(0.0, -13.0)], // wraith
    &[(0.0, -14.0)], // warden
    &[(-3.0, -14.0), (3.0, -14.0)], // ravager
    &[(0.0, -14.0)], // glacier
    &[(-3.0, -16.0), (3.0, -16.0)], // obelisk
    &[(-5.0, -16.0), (5.0, -16.0)], // titan
    &[(0.0, -17.0)], // leviathan
];

/// The minigun module's muzzle, where its bullets leave (turret frame).
pub const MINIGUN_MUZZLE: [(f32, f32); 12] = [
    (5.5, -6.0), // scout
    (6.5, -6.0), // assault
    (6.5, -7.0), // breaker
    (5.5, -9.0), // longbow
    (6.5, -8.0), // flak
    (5.5, -6.0), // wraith
    (6.5, -7.0), // warden
    (6.5, -7.0), // ravager
    (6.5, -6.0), // glacier
    (7.5, -7.0), // obelisk
    (8.5, -6.0), // titan
    (8.5, -8.0), // leviathan
];

/// The laser module's lens, where its beam starts (turret frame).
pub const LASER_MUZZLE: [(f32, f32); 12] = [
    (-6.0, -4.0), // scout
    (-7.0, -6.0), // assault
    (-6.0, -7.0), // breaker
    (-6.0, -9.0), // longbow
    (-7.0, -8.0), // flak
    (-6.0, -6.0), // wraith
    (-6.0, -7.0), // warden
    (-6.0, -7.0), // ravager
    (-7.0, -6.0), // glacier
    (-8.0, -7.0), // obelisk
    (-8.0, -6.0), // titan
    (-9.0, -8.0), // leviathan
];

/// The flamethrower module's nozzle, where its jet starts (turret frame).
pub const FLAME_MUZZLE: [(f32, f32); 12] = [
    (-5.5, -2.0), // scout
    (-6.5, -2.0), // assault
    (-5.5, -2.0), // breaker
    (-5.5, -2.0), // longbow
    (-6.5, -3.0), // flak
    (-5.5, -3.0), // wraith
    (-5.5, -2.0), // warden
    (-5.5, -2.0), // ravager
    (-6.5, -3.0), // glacier
    (-7.5, -4.0), // obelisk
    (-7.5, -2.0), // titan
    (-8.5, -3.0), // leviathan
];

/// The grenade launcher module's barrel mouth, where its grenades leave (turret frame).
pub const GRENADE_MUZZLE: [(f32, f32); 12] = [
    (0.5, -4.0), // scout
    (0.5, -3.0), // assault
    (0.5, -5.0), // breaker
    (0.5, -3.0), // longbow
    (0.5, -5.0), // flak
    (0.5, -5.0), // wraith
    (0.5, -5.0), // warden
    (0.5, -5.0), // ravager
    (0.5, -4.0), // glacier
    (0.5, -7.0), // obelisk
    (0.5, -4.0), // titan
    (0.5, -3.0), // leviathan
];

/// The sonic hammer module's dish, where its wind-up is drawn (turret frame).
pub const SONIC_MUZZLE: [(f32, f32); 12] = [
    (0.5, -2.0), // scout
    (0.5, -1.0), // assault
    (0.5, -3.0), // breaker
    (0.5, -1.0), // longbow
    (0.5, -3.0), // flak
    (0.5, -3.0), // wraith
    (0.5, -3.0), // warden
    (0.5, -3.0), // ravager
    (0.5, -2.0), // glacier
    (0.5, -5.0), // obelisk
    (0.5, -2.0), // titan
    (0.5, -1.0), // leviathan
];

/// The EMP module's coil centre, where its crackle is drawn (turret frame).
pub const EMP_COIL: [(f32, f32); 12] = [
    (0.5, 2.5), // scout
    (0.5, 3.5), // assault
    (0.5, 1.5), // breaker
    (0.5, 3.5), // longbow
    (0.5, 1.5), // flak
    (0.5, 1.5), // wraith
    (0.5, 1.5), // warden
    (0.5, 1.5), // ravager
    (0.5, 2.5), // glacier
    (0.5, -0.5), // obelisk
    (0.5, 2.5), // titan
    (0.5, 3.5), // leviathan
];

/// The gauss rail module's bore mouth, where its slug is drawn from (turret frame).
pub const RAIL_MUZZLE: [(f32, f32); 12] = [
    (-5.5, -5.0), // scout
    (-6.5, -7.0), // assault
    (-5.5, -8.0), // breaker
    (-5.5, -10.0), // longbow
    (-6.5, -9.0), // flak
    (-5.5, -7.0), // wraith
    (-5.5, -8.0), // warden
    (-5.5, -8.0), // ravager
    (-6.5, -7.0), // glacier
    (-7.5, -8.0), // obelisk
    (-7.5, -7.0), // titan
    (-8.5, -9.0), // leviathan
];

/// The rod uplink's designator lens, where its line to the reticle is drawn from (turret frame).
pub const ROD_LENS: [(f32, f32); 12] = [
    (0.5, -0.5), // scout
    (0.5, 0.5), // assault
    (0.5, -1.5), // breaker
    (0.5, 0.5), // longbow
    (0.5, -1.5), // flak
    (0.5, -1.5), // wraith
    (0.5, -1.5), // warden
    (0.5, -1.5), // ravager
    (0.5, -0.5), // glacier
    (0.5, -3.5), // obelisk
    (0.5, -0.5), // titan
    (0.5, 0.5), // leviathan
];

/// The missile launcher's four tube mouths, in firing order (turret frame).
pub const MISSILE_TUBES: [[(f32, f32); 4]; 12] = [
    [(-1.0, 1.0), (1.0, 1.0), (-1.0, 3.0), (1.0, 3.0)], // scout
    [(-1.0, 2.0), (1.0, 2.0), (-1.0, 4.0), (1.0, 4.0)], // assault
    [(-1.0, 0.0), (1.0, 0.0), (-1.0, 2.0), (1.0, 2.0)], // breaker
    [(-1.0, 2.0), (1.0, 2.0), (-1.0, 4.0), (1.0, 4.0)], // longbow
    [(-1.0, 0.0), (1.0, 0.0), (-1.0, 2.0), (1.0, 2.0)], // flak
    [(-1.0, 0.0), (1.0, 0.0), (-1.0, 2.0), (1.0, 2.0)], // wraith
    [(-1.0, 0.0), (1.0, 0.0), (-1.0, 2.0), (1.0, 2.0)], // warden
    [(-1.0, 0.0), (1.0, 0.0), (-1.0, 2.0), (1.0, 2.0)], // ravager
    [(-1.0, 1.0), (1.0, 1.0), (-1.0, 3.0), (1.0, 3.0)], // glacier
    [(-1.0, -2.0), (1.0, -2.0), (-1.0, 0.0), (1.0, 0.0)], // obelisk
    [(-1.0, 1.0), (1.0, 1.0), (-1.0, 3.0), (1.0, 3.0)], // titan
    [(-1.0, 2.0), (1.0, 2.0), (-1.0, 4.0), (1.0, 4.0)], // leviathan
];
